mpc:
  id: cartpole
  # acados_settings:
  meta:
    json_file: config/cartpole_ocp.json
  ocp_options:
    tf: 3.0
    qp_solver: PARTIAL_CONDENSING_HPIPM
    hessian_approx: GAUSS_NEWTON
    integrator_type: ERK
    nlp_solver_type: SQP
    nlp_solver_max_iter: 200
    qp_solver_iter_max: 200

  dimensions:
    nx: 4
    nu: 1
    N: 30
  cost:
    cost_type: LINEAR_LS
    cost_type_e: LINEAR_LS
    Q: [100.0, 0.1, 100.0, 0.1] # state cost
    R: [0.001] # control cost
    Q_e: [100.0, 0.1, 100.0, 0.1] # terminal state cost
  model:
    name: cartpole_ode
    M: 1.0 # mass of the cart
    m: 0.1 # mass of the ball
    l: 0.5 # length of the pole
    g: 9.8 # gravity
  constraints:
    constraint_type: BGH
    x0: [0.0, 0.0, 3.14, 0.0]
    lbu: [-30.0] # lower bound of control input
    ubu: [30.0] # upper bound of control input

environment:
  id: ContinuousCartPoleSwingUpEnv-v0
  render_mode: rgb_array
  force_mag: 30.0

learning_rate: 0.001
